import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import {Theme} from "@radix-ui/themes";
import { ThemeProvider } from 'next-themes'
import ThemeToggle from "@/app/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Site recreation with NextJS & ReactJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
        >
          <Theme accentColor="lime" grayColor="olive" radius="full" scaling="90%">
            {children}
          <div className="absolute top-4 right-4">
            <ThemeToggle />
          </div>
          </Theme>
        </ThemeProvider>

      </body>
    </html>
  );
}
